/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mousemovergui;

import mousemover.exception.AliveException;
import mousemover.MouseMover;
import mousemover.exception.NotAliveException;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author WINDOWS 10
 */
public class MouseMoverGUI extends javax.swing.JFrame {

    /**
     * Creates new form EasyAFKGUI
     */
    public MouseMoverGUI() {
        
        styleComponents();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void styleComponents(){
        UIManager.put("OptionPane.messageFont", new Font("Consolas", Font.PLAIN, 14));
        UIManager.put("OptionPane.buttonFont", new Font("Consolas", Font.PLAIN, 14));
 
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");  // This line gives Windows Theme
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MouseMoverGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        setIconImage(new ImageIcon(getClass().getResource("/resource/icon.png")).getImage());
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEnableButton = new javax.swing.JButton();
        jDisableButton = new javax.swing.JButton();
        jStatusLabel = new javax.swing.JLabel();
        jStatus = new javax.swing.JLabel();
        jIntervalButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mouse Mover");
        setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        setForeground(java.awt.Color.lightGray);

        jEnableButton.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jEnableButton.setText("Enable");
        jEnableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEnableButtonActionPerformed(evt);
            }
        });

        jDisableButton.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jDisableButton.setText("Disable");
        jDisableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDisableButtonActionPerformed(evt);
            }
        });

        jStatusLabel.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jStatusLabel.setText("Status:");

        jStatus.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jStatus.setText("Disabled      ");

        jIntervalButton.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jIntervalButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/gear.png"))); // NOI18N
        jIntervalButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jIntervalButton.setIconTextGap(1);
        jIntervalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIntervalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDisableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jEnableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(jStatusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jStatus)
                    .addComponent(jIntervalButton))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEnableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStatusLabel)
                    .addComponent(jStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDisableButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jIntervalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jEnableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEnableButtonActionPerformed
        try {
            MouseMover.enable();
            jStatus.setText("Enabled");
        } catch (AliveException ex) {
            jStatus.setText("Already Enabled");
        }
    }//GEN-LAST:event_jEnableButtonActionPerformed

    private void jDisableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDisableButtonActionPerformed
        try {
            MouseMover.disable();
            jStatus.setText("Disabled");
        } catch (NotAliveException ex) {
            jStatus.setText("Not Enabled");
        }
    }//GEN-LAST:event_jDisableButtonActionPerformed

    private void jIntervalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIntervalButtonActionPerformed
        String stringInput = (String) JOptionPane.showInputDialog(this,"Set Interval in seconds:\nCurrent: " + String.valueOf(MouseMover.getInterval() / 1000) + " s\nMinimum: 3 s","Mouse Mover Interval",JOptionPane.QUESTION_MESSAGE,new ImageIcon(getClass().getResource("/resource/gear.png")),null,"");
        
        try {
            Long longInput = Long.parseLong(stringInput);
            if (longInput < 3) {
                MouseMover.setInterval(3000l);
            } else {
                MouseMover.setInterval(longInput * 1000);
            }
        } catch (NumberFormatException e) {

        }
    }//GEN-LAST:event_jIntervalButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MouseMoverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MouseMoverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MouseMoverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MouseMoverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MouseMoverGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jDisableButton;
    private javax.swing.JButton jEnableButton;
    private javax.swing.JButton jIntervalButton;
    private javax.swing.JLabel jStatus;
    private javax.swing.JLabel jStatusLabel;
    // End of variables declaration//GEN-END:variables
}
